name = "client-yysng-site"
compatibility_date = "2026-02-26"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "CONTACTS_KV", id = "c883891654e44a3ab6633c2a9e84cde9", preview_id = "c883891654e44a3ab6633c2a9e84cde9" }
]